language: node_js
node_js:
  - "20"
  - "18"
  - "16"
# copied from https://github.com/greenkeeperio/greenkeeper-lockfile
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload